include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  errors:
    depend_on_referenced_packages: ignore
    lines_longer_than_80_chars: ignore
  exclude:
    - lib/l10n/*
    - lib/generated/*
    - lib/**/*.g.dart
    - assets/**/*.gen.dart
    - packages/**/*.gen.dart
linter:
  rules:
    public_member_api_docs: false
